name = "promptly"
version = "1.0.1"

description = "Validated user input."
licences = ["Apache-2.0"]
repository = { type = "github", user = "JosephTLyons", repo = "promptly" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
input = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
